### ISSUE TITLE
Charts Components

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#1]
D3.js v4 charts designed for Material Design

**Comment by kyleledbetter** [comment]
-[ ] core td-chart component w/ core scss
-[ ] td-chart-line
-[ ] td-chart-area
-[ ] td-chart-bar
-[ ] td-chart-treemap
-[ ] td-chart-bullet
-[ ] td-chart-chord
-[ ] td-chart-forcedirected
-[ ] td-chart-bubble
-[ ] td-chart-circlepacking
-[ ] td-chart-nodelink
-[ ] td-chart-dendrogram

**Comment by kyleledbetter** [comment]
Options & Attributes:

- [ ] stacked
- [ ] combo chart
- [ ] dual axis
- [ ] horizontal bar
- [ ] zoomable
- [ ] SVG shadow/filter (with depth)
- [ ] viewfinder (mini chart)
- [ ] colors (array on td-chart, or individual in each chart)

**Comment by kyleledbetter** [comment]
track progress here https://github.com/Teradata/covalent/commits/feature/charts

**Comment by kyleledbetter** [comment]
for the SVG Drop Shadow `<filter>`
http://bl.ocks.org/cpbotha/5200394

we’d need to tweak `height` `stdDeviation` (blur) and `dy` (vertical distance) to achieve the different material z-depths

also we’d need to increment the ID for each chart on the page so the ID can be unique for each chart

**Comment by kyleledbetter** [comment]
### Statistics
optional gridlines on either axis for:

- [ ] min
- [ ] max
- [ ] mean (average)
- [ ] median (midpoint)
- [ ] standard deviation

from:
https://github.com/d3/d3-array/blob/master/README.md#statistics

**Comment by kyleledbetter** [comment]
### Random Numbers

it would be nice to have an attribute to talks to a function to generate random numbers on each chart series using:

https://github.com/d3/d3-random

**Comment by kyleledbetter** [comment]
closed with https://github.com/Teradata/covalent/pull/52
