### ISSUE TITLE
Material Motion (angular2 page animations)

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#51]
use to be called "meaningful transitions"
From the spec:
https://material.google.com/motion/material-motion.html
applying to angular2 using https://angular.io/docs/ts/latest/guide/animations.html

possibly using `onActivate` and `onDeactivate`
from http://stackoverflow.com/posts/33554846/revisions

with the goals of these animation options:
- [ ] object (using directives?)
- [ ]  pages (using on router-outlet?)
- [ ]  grow/shrink (from point of origin)
- [ ]  from item to view (point of origin w/ hierarchy)
- [ ] simple page transitions (crossfade/right->left/left->right/top->bottom/bottom->top)

**Comment by emoralesb05** [comment]
We can use https://angular.io/docs/ts/latest/guide/router.html#!#route-animation

**Comment by kyleledbetter** [comment]
first step taken https://github.com/Teradata/covalent/pull/220

**Comment by jeremysmartt** [comment]
Closing as duplicated by #49 and other animation tickets
